#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Drop.Landing;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!-- START APP SHOTS-->\r\n<section");

WriteLiteral(" id=\"versions\"");

WriteLiteral(" class=\"versions\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <!-- START SECTION HEADER-->\r\n        <div");

WriteLiteral(" data-wow-offset=\"120\"");

WriteLiteral(" data-wow-duration=\"1.3s\"");

WriteLiteral(" class=\"section-header wow fadeIn animated\"");

WriteLiteral(">\r\n            <!-- SECTION TITLE-->\r\n            <h2>Son takip edilen ürünler</h" +
"2>\r\n            <div");

WriteLiteral(" class=\"section-description\"");

WriteLiteral(">Sen de hemen ürününü takip et ve indirim bildirimlerimizle kazanmaya başla. </di" +
"v>\r\n        </div>\r\n        <!-- END SECTION HEADER-->\r\n        <div");

WriteLiteral(" class=\"row bottom-space\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"col-lg-4 col-sm-6 col-xs-12\"");

WriteLiteral(" ng-repeat=\"product in ctrl.recentProducts\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"media media-card\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"media-left media-middle\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" ng-src=\"{{product.image_url}}\"");

WriteLiteral(" width=\"128\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" data-no-retina=\"\"");

WriteLiteral(" data-wow-offset=\"15\"");

WriteLiteral(" data-wow-duration=\".5s\"");

WriteLiteral(" class=\"wow zoomIn animated img-responsive version-pic\"");

WriteLiteral(">\r\n                        </a>\r\n                    </div>\r\n                    " +
"<div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                        <h5");

WriteLiteral(" class=\"media-heading\"");

WriteLiteral(" style=\"color:black\"");

WriteLiteral(">{{product.web_site_name}}</h5>\r\n                        <p");

WriteLiteral(" class=\"media-card-text\"");

WriteLiteral(">{{product.name.length>15 ? product.name.substring(0,15)+\'...\' : product.name}}</" +
"p>\r\n                        <h5");

WriteLiteral(" class=\"media-heading\"");

WriteLiteral(">{{product.price+\' \'+product.currency}}</h5>\r\n                        <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1547), Tuple.Create("\"", 1603)
            
            #line 30 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1554), Tuple.Create<System.Object, System.Int32>(Url.Action("Detail","Product")
            
            #line default
            #line hidden
, 1554), false)
, Tuple.Create(Tuple.Create("", 1585), Tuple.Create("?id={{product.id}}", 1585), true)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn btn-sm btn-default\"");

WriteLiteral(">Detay</a>\r\n                        </div>\r\n                    </div>\r\n         " +
"       </div>\r\n            </div>\r\n        </div>\r\n\r\n        <!-- START SECTION " +
"HEADER-->\r\n        <div");

WriteLiteral(" data-wow-offset=\"120\"");

WriteLiteral(" data-wow-duration=\"1.3s\"");

WriteLiteral(" class=\"section-header wow fadeIn animated\"");

WriteLiteral(">\r\n            <!-- SECTION TITLE-->\r\n            <h2>En çok takip edilen ürünler" +
"</h2>\r\n            <div");

WriteLiteral(" class=\"section-description\"");

WriteLiteral(">Sen de hemen ürününü takip et ve indirim bildirimlerimizle kazanmaya başla. </di" +
"v>\r\n        </div>\r\n        <!-- END SECTION HEADER-->\r\n        <div");

WriteLiteral(" class=\"row bottom-space\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"col-lg-4 col-sm-6 col-xs-12\"");

WriteLiteral(" ng-repeat=\"product in ctrl.topFollowedProducts\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"media media-card\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"media-left media-middle\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" ng-src=\"{{product.image_url}}\"");

WriteLiteral(" width=\"128px\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" data-no-retina=\"\"");

WriteLiteral(" data-wow-offset=\"15\"");

WriteLiteral(" data-wow-duration=\".5s\"");

WriteLiteral(" class=\"wow zoomIn animated img-responsive version-pic\"");

WriteLiteral(">\r\n                        </a>\r\n                    </div>\r\n                    " +
"<div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\"media-heading\"");

WriteLiteral(">{{product.web_site_name}}</h4>\r\n                        <p");

WriteLiteral(" class=\"media-card-text\"");

WriteLiteral(">{{product.name.length>15 ? product.name.substring(0,15)+\'...\' : product.name}}</" +
"p>\r\n                        <h5");

WriteLiteral(" class=\"media-heading\"");

WriteLiteral(">{{product.price+\' \'+product.currency}}</h5>\r\n                        <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"{{product.url}}\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn btn-sm btn-default\"");

WriteLiteral(">Git</a>\r\n                        </div>\r\n                    </div>\r\n           " +
"     </div>\r\n            </div>\r\n        </div>\r\n\r\n    </div>\r\n</section>\r\n<!-- " +
"START FEATURE LIST-->\r\n<section");

WriteLiteral(" id=\"features\"");

WriteLiteral(" class=\"features-list\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <!-- START SECTION HEADER-->\r\n        <div");

WriteLiteral(" data-wow-offset=\"120\"");

WriteLiteral(" data-wow-duration=\"1.3s\"");

WriteLiteral(" class=\"section-header wow fadeIn animated\"");

WriteLiteral(">\r\n            <!-- SECTION TITLE-->\r\n            <h2>Uygulama Özellikleri</h2>\r\n" +
"            <div");

WriteLiteral(" class=\"section-description\"");

WriteLiteral(">Hızlı ve kolay takip sistemiyle en uygun fiyata alışveriş yapmanı sağlıyoruz.</d" +
"iv>\r\n        </div>\r\n        <!-- END SECTION HEADER-->\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <!-- START FEATURES LEFT-->\r\n            <div");

WriteLiteral(" class=\"col-md-4 col-sm-4 features-left\"");

WriteLiteral(">\r\n                <!-- FEATURE-->\r\n                <div");

WriteLiteral(" class=\"feature\"");

WriteLiteral(">\r\n                    <!-- FEATURE ICON-->\r\n                    <div");

WriteLiteral(" data-wow-offset=\"15\"");

WriteLiteral(" data-wow-duration=\"1.3s\"");

WriteLiteral(" class=\"feature-icon wow fadeIn animated\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"fa-stack fa-lg\"");

WriteLiteral(">\r\n                            <em");

WriteLiteral(" class=\"fa fa-circle fa-stack-2x\"");

WriteLiteral("></em>\r\n                            <em");

WriteLiteral(" class=\"fa fa-random fa-stack-1x fa-inverse\"");

WriteLiteral("></em>\r\n                        </span>\r\n                    </div>\r\n            " +
"        <!-- FEATURE TEXT-->\r\n                    <div");

WriteLiteral(" class=\"feature-details\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\"main-color\"");

WriteLiteral(">Kolay Takip</h4>\r\n                        <p>Takip etmek istediğin ürünün adresi" +
"ni sisteme girmen yeterli</p>\r\n                    </div>\r\n                </div" +
">\r\n                <!-- FEATURE-->\r\n                <div");

WriteLiteral(" class=\"feature\"");

WriteLiteral(">\r\n                    <!-- FEATURE ICON-->\r\n                    <div");

WriteLiteral(" data-wow-offset=\"15\"");

WriteLiteral(" data-wow-duration=\"1.3s\"");

WriteLiteral(" class=\"feature-icon wow fadeIn animated\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"fa-stack fa-lg\"");

WriteLiteral(">\r\n                            <em");

WriteLiteral(" class=\"fa fa-circle fa-stack-2x\"");

WriteLiteral("></em>\r\n                            <em");

WriteLiteral(" class=\"fa fa-rocket fa-stack-1x fa-inverse\"");

WriteLiteral("></em>\r\n                        </span>\r\n                    </div>\r\n            " +
"        <!-- FEATURE TEXT-->\r\n                    <div");

WriteLiteral(" class=\"feature-details\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\"main-color\"");

WriteLiteral(">Özelliştirme</h4>\r\n                        <p>İstediğin orana göre indirim bildi" +
"rimi alabilirsin. </p>\r\n                    </div>\r\n                </div>\r\n    " +
"            <!-- FEATURE-->\r\n                <div");

WriteLiteral(" class=\"feature\"");

WriteLiteral(">\r\n                    <!-- FEATURE ICON-->\r\n                    <div");

WriteLiteral(" data-wow-offset=\"15\"");

WriteLiteral(" data-wow-duration=\"1.3s\"");

WriteLiteral(" class=\"feature-icon wow fadeIn animated\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"fa-stack fa-lg\"");

WriteLiteral(">\r\n                            <em");

WriteLiteral(" class=\"fa fa-circle fa-stack-2x\"");

WriteLiteral("></em>\r\n                            <em");

WriteLiteral(" class=\"fa fa-crosshairs fa-stack-1x fa-inverse\"");

WriteLiteral("></em>\r\n                        </span>\r\n                    </div>\r\n            " +
"        <!-- FEATURE TEXT-->\r\n                    <div");

WriteLiteral(" class=\"feature-details\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\"main-color\"");

WriteLiteral(@">Ortam Bağımsız</h4>
                        <p>Evde, işte veya cepte istediğin yerde hesabınla sisteme girip ürünlerini takip edebilirsin.</p>
                    </div>
                </div>
            </div>
            <!-- END FEATURES LEFT-->
            <!-- START MOBILE MOCKUP-->
            <div");

WriteLiteral(" class=\"col-md-4 col-sm-4\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" data-wow-offset=\"120\"");

WriteLiteral(" data-wow-duration=\"1.3s\"");

WriteLiteral(" class=\"mockup-mobile wow fadeIn animated\"");

WriteLiteral(">\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6763), Tuple.Create("\"", 6817)
            
            #line 130 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 6769), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/img/iphone-minimal.png")
            
            #line default
            #line hidden
, 6769), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" data-no-retina>\r\n                </div>\r\n            </div>\r\n            <!-- EN" +
"D MOBILE MOCKUP-->\r\n            <!-- START FEATURES RIGHT-->\r\n            <div");

WriteLiteral(" class=\"col-md-4 col-sm-4 features-right\"");

WriteLiteral(">\r\n                <!-- FEATURE-->\r\n                <div");

WriteLiteral(" class=\"feature\"");

WriteLiteral(">\r\n                    <!-- FEATURE ICON-->\r\n                    <div");

WriteLiteral(" data-wow-offset=\"15\"");

WriteLiteral(" data-wow-duration=\"1.3s\"");

WriteLiteral(" class=\"feature-icon wow fadeIn animated\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"fa-stack fa-lg\"");

WriteLiteral(">\r\n                            <em");

WriteLiteral(" class=\"fa fa-circle fa-stack-2x\"");

WriteLiteral("></em>\r\n                            <em");

WriteLiteral(" class=\"fa fa-moon-o fa-stack-1x fa-inverse\"");

WriteLiteral("></em>\r\n                        </span>\r\n                    </div>\r\n            " +
"        <!-- FEATURE TEXT-->\r\n                    <div");

WriteLiteral(" class=\"feature-details\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\"main-color\"");

WriteLiteral(">Bildirim Kolaylığı</h4>\r\n                        <p>Bildirimlerini Mobil, Web ve" +
" E-posta ile kolayca alabilirsin.</p>\r\n                    </div>\r\n             " +
"   </div>\r\n                <!-- FEATURE-->\r\n                <div");

WriteLiteral(" class=\"feature\"");

WriteLiteral(">\r\n                    <!-- FEATURE ICON-->\r\n                    <div");

WriteLiteral(" data-wow-offset=\"15\"");

WriteLiteral(" data-wow-duration=\"1.3s\"");

WriteLiteral(" class=\"feature-icon wow fadeIn animated\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"fa-stack fa-lg\"");

WriteLiteral(">\r\n                            <em");

WriteLiteral(" class=\"fa fa-circle fa-stack-2x\"");

WriteLiteral("></em>\r\n                            <em");

WriteLiteral(" class=\"fa fa-sitemap fa-stack-1x fa-inverse\"");

WriteLiteral("></em>\r\n                        </span>\r\n                    </div>\r\n            " +
"        <!-- FEATURE TEXT-->\r\n                    <div");

WriteLiteral(" class=\"feature-details\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\"main-color\"");

WriteLiteral(@">Geniş ürün yelpazesi</h4>
                        <p>Bırak raqun senin için 100'den fazla eticaret sitesi üzerinden en uygun fiyatı bulmana yardımcı olsun!</p>
                    </div>
                </div>
                <!-- FEATURE-->
                <div");

WriteLiteral(" class=\"feature\"");

WriteLiteral(">\r\n                    <!-- FEATURE ICON-->\r\n                    <div");

WriteLiteral(" data-wow-offset=\"15\"");

WriteLiteral(" data-wow-duration=\"1.3s\"");

WriteLiteral(" class=\"feature-icon wow fadeIn animated\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"fa-stack fa-lg\"");

WriteLiteral(">\r\n                            <em");

WriteLiteral(" class=\"fa fa-circle fa-stack-2x\"");

WriteLiteral("></em>\r\n                            <em");

WriteLiteral(" class=\"fa fa-wrench fa-stack-1x fa-inverse\"");

WriteLiteral("></em>\r\n                        </span>\r\n                    </div>\r\n            " +
"        <!-- FEATURE TEXT-->\r\n                    <div");

WriteLiteral(" class=\"feature-details\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\"main-color\"");

WriteLiteral(@">Fiyat Hareketleri</h4>
                        <p>Ürün fiyat değişiklerini kolayca takip edebilirsiniz.</p>
                    </div>
                </div>
            </div>
            <!-- END FEATURES RIGHT-->
        </div>
    </div>
</section>
<!-- END FEATURE LIST-->
<!-- START PIC TEXT LEFT-->
<section");

WriteLiteral(" id=\"desc2\"");

WriteLiteral(" class=\"pic-text pic-text-left\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <!-- LEFT PIC-->\r\n            <div");

WriteLiteral(" data-wow-offset=\"15\"");

WriteLiteral(" data-wow-duration=\"1.2s\"");

WriteLiteral(" class=\"col-md-6 wow fadeInLeft animated\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"mockup-mobile\"");

WriteLiteral(">\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 9962), Tuple.Create("\"", 10010)
            
            #line 194 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 9968), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/img/ipad-air.png")
            
            #line default
            #line hidden
, 9968), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" data-no-retina>\r\n                </div>\r\n            </div>\r\n            <!-- RI" +
"GHT TEXT-->\r\n            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(@">
                <!-- SECTION TITLE-->
                <h2>raqun nedir?</h2>
                <p>Satın almak istediğin ürünü takibe alarak indirimli almana olanak sağlıyoruz.Tek yapman gereken üye olup hemen takip etmek istediğin ürünün adresini sisteme girmen. 100'den fazla eticaret sitesi takibi yapan raqun; indirim olduğunda seni bildirimlerle uyaracak.</p>
                <!-- FEATURE LIST-->
                <ul");

WriteLiteral(" class=\"featured-list\"");

WriteLiteral(">\r\n                    <li>\r\n                        <span");

WriteLiteral(" class=\"fa-stack fa-lg\"");

WriteLiteral(">\r\n                            <em");

WriteLiteral(" class=\"fa fa-circle fa-stack-2x\"");

WriteLiteral("></em>\r\n                            <em");

WriteLiteral(" class=\"fa fa-money fa-stack-1x fa-inverse\"");

WriteLiteral("></em>\r\n                        </span>\r\n                        <p>Hızlı Kazanç<" +
"/p>\r\n                    </li>\r\n                    <li>\r\n                      " +
"  <span");

WriteLiteral(" class=\"fa-stack fa-lg\"");

WriteLiteral(">\r\n                            <em");

WriteLiteral(" class=\"fa fa-circle fa-stack-2x\"");

WriteLiteral("></em>\r\n                            <em");

WriteLiteral(" class=\"fa fa-user fa-stack-1x fa-inverse\"");

WriteLiteral("></em>\r\n                        </span>\r\n                        <p>Hızlı Üyelik<" +
"/p>\r\n                    </li>\r\n                    <li>\r\n                      " +
"  <span");

WriteLiteral(" class=\"fa-stack fa-lg\"");

WriteLiteral(">\r\n                            <em");

WriteLiteral(" class=\"fa fa-circle fa-stack-2x\"");

WriteLiteral("></em>\r\n                            <em");

WriteLiteral(" class=\"fa fa-bullhorn fa-stack-1x fa-inverse\"");

WriteLiteral(@"></em>
                        </span>
                        <p>Hızlı Bildirim</p>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</section>
<!-- END PIC TEXT LEFT-->
<!-- START PIC TEXT RIGHT-->
");

WriteLiteral("\r\n<!-- END PIC TEXT RIGHT-->\r\n<!-- START APP SHOTS-->\r\n");

WriteLiteral("\r\n<!-- END APP SHOTS-->\r\n<!-- START TESTIMONIAL SLIDER-->\r\n");

WriteLiteral("\r\n<!-- END TESTIMONIAL SLIDER-->\r\n<!-- START PLAN TABLE-->\r\n");

WriteLiteral("\r\n<!-- END PLAN TABLE-->\r\n<!-- START DOWNLOAD-->\r\n<section");

WriteLiteral(" id=\"download\"");

WriteLiteral(" class=\"download\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <h2");

WriteLiteral(" data-wow-offset=\"15\"");

WriteLiteral(" data-wow-duration=\"1.2s\"");

WriteLiteral(" class=\"wow fadeInDown animated\"");

WriteLiteral(">Raqun mobil uygulamasını hemen indirmek için</h2>\r\n            <div");

WriteLiteral(" data-wow-offset=\"15\"");

WriteLiteral(" data-wow-duration=\"1.2s\"");

WriteLiteral(" class=\"wow fadeInUp animated\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"https://wrapbootstrap.com/theme/angle-bootstrap-admin-app-angularjs-WB04HF" +
"123\"");

WriteLiteral(" class=\"btn btn-lg\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 26294), Tuple.Create("\"", 26329)
, Tuple.Create(Tuple.Create("", 26300), Tuple.Create<System.Object, System.Int32>(Href("~/Content/img/google-play.png")
, 26300), false)
);

WriteLiteral(" />\r\n                </a>\r\n                <a");

WriteLiteral(" href=\"https://wrapbootstrap.com/theme/angle-bootstrap-admin-app-angularjs-WB04HF" +
"123\"");

WriteLiteral(" class=\"btn btn-lg\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 26573), Tuple.Create("\"", 26606)
, Tuple.Create(Tuple.Create("", 26579), Tuple.Create<System.Object, System.Int32>(Href("~/Content/img/app-store.png")
, 26579), false)
);

WriteLiteral(" />\r\n                </a>\r\n            </div>\r\n        </div>\r\n    </section>\r\n<!" +
"-- END DOWNLOAD-->\r\n<!-- START PRODUCTS-->\r\n");

WriteLiteral("\r\n<!-- START PLAN TABLE-->\r\n");

WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
