#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Drop.Landing;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Product/Detail.cshtml")]
    public partial class _Views_Product_Detail_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Product_Detail_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Product\Detail.cshtml"
  
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_ProductLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    h5 {\r\n        font-size: 12px;\r\n    }\r\n</style>\r\n<div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(" ng-cloak");

WriteLiteral(" ng-controller=\"ProductDetailController as ctrl\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-lg-3 hidden-xs\"");

WriteLiteral(">\r\n            <!-- START List group-->\r\n            <ul");

WriteLiteral(" class=\"list-group\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row row-table pv-lg\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"m0 lead\"");

WriteLiteral(">1500</p>\r\n                            <p");

WriteLiteral(" class=\"m0\"");

WriteLiteral(">\r\n                                <small>ürün</small>\r\n                         " +
"   </p>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-6 text-center\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" data-sparkline=\"\"");

WriteLiteral(" data-bar-color=\"#23b7e5\"");

WriteLiteral(" data-height=\"60\"");

WriteLiteral(" data-bar-width=\"10\"");

WriteLiteral(" data-bar-spacing=\"6\"");

WriteLiteral(" data-chart-range-min=\"0\"");

WriteLiteral(" values=\"3,6,7,8,4,5\"");

WriteLiteral("></div>\r\n                        </div>\r\n                    </div>\r\n            " +
"    </li>\r\n                <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row row-table pv-lg\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                            <h5>Fiyat Değişimi</h5>\r\n                         " +
"   <ul");

WriteLiteral(" class=\"list-group\"");

WriteLiteral(">\r\n                                <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(" ng-repeat=\"priceHis in ctrl.product.histories\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">{{priceHis.price}} TL <span");

WriteLiteral(" class=\"label label-info pull-right\"");

WriteLiteral(">{{priceHis.created_at | date:\'MM.yyyy\'}}</span></div>\r\n                         " +
"       </li>\r\n                            </ul>\r\n                        </div>\r" +
"\n\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"row row-table pv-lg\"");

WriteLiteral(" ng-show=\"ctrl.product.histories.length>1\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12 text-center\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" data-sparkline=\"\"");

WriteLiteral(" data-type=\"line\"");

WriteLiteral(" data-height=\"60\"");

WriteLiteral(" data-width=\"80%\"");

WriteLiteral(" data-line-width=\"2\"");

WriteLiteral(" data-line-color=\"#7266ba\"");

WriteLiteral(" data-chart-range-min=\"90\"");

WriteLiteral(" data-spot-color=\"#888\"");

WriteLiteral(" data-min-spot-color=\"#7266ba\"");

WriteLiteral(" data-max-spot-color=\"#7266ba\"");

WriteLiteral("\r\n                                 data-fill-color=\"\"");

WriteLiteral(" data-highlight-line-color=\"#fff\"");

WriteLiteral(" data-spot-radius=\"3\"");

WriteLiteral(" values=\"{{productPrices}}\"");

WriteLiteral(" data-resize=\"true\"");

WriteLiteral("></div>\r\n                        </div>\r\n                    </div>\r\n            " +
"    </li>\r\n                <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row row-table pv-lg\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"m0 lead\"");

WriteLiteral(">44</p>\r\n                            <p");

WriteLiteral(" class=\"m0\"");

WriteLiteral(">\r\n                                <small>yeni üye</small>\r\n                     " +
"       </p>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n                            <ul");

WriteLiteral(" class=\"list-inline text-center\"");

WriteLiteral(">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" tooltip=\"Katie\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3046), Tuple.Create("\"", 3100)
            
            #line 60 "..\..\Views\Product\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 3052), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ProductContent/img/user/02.jpg")
            
            #line default
            #line hidden
, 3052), false)
);

WriteLiteral(" alt=\"Follower\"");

WriteLiteral(" class=\"img-responsive img-circle thumb24\"");

WriteLiteral(">\r\n                                    </a>\r\n                                </li" +
">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" tooltip=\"Cody\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3389), Tuple.Create("\"", 3443)
            
            #line 65 "..\..\Views\Product\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 3395), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ProductContent/img/user/01.jpg")
            
            #line default
            #line hidden
, 3395), false)
);

WriteLiteral(" alt=\"Follower\"");

WriteLiteral(" class=\"img-responsive img-circle thumb24\"");

WriteLiteral(">\r\n                                    </a>\r\n                                </li" +
">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" tooltip=\"Tamara\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3734), Tuple.Create("\"", 3788)
            
            #line 70 "..\..\Views\Product\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 3740), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ProductContent/img/user/03.jpg")
            
            #line default
            #line hidden
, 3740), false)
);

WriteLiteral(" alt=\"Follower\"");

WriteLiteral(" class=\"img-responsive img-circle thumb24\"");

WriteLiteral(">\r\n                                    </a>\r\n                                </li" +
">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" tooltip=\"Gene\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4077), Tuple.Create("\"", 4131)
            
            #line 75 "..\..\Views\Product\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 4083), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ProductContent/img/user/04.jpg")
            
            #line default
            #line hidden
, 4083), false)
);

WriteLiteral(" alt=\"Follower\"");

WriteLiteral(" class=\"img-responsive img-circle thumb24\"");

WriteLiteral(">\r\n                                    </a>\r\n                                </li" +
">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" tooltip=\"Marsha\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4422), Tuple.Create("\"", 4476)
            
            #line 80 "..\..\Views\Product\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 4428), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ProductContent/img/user/04.jpg")
            
            #line default
            #line hidden
, 4428), false)
);

WriteLiteral(" alt=\"Follower\"");

WriteLiteral(" class=\"img-responsive img-circle thumb24\"");

WriteLiteral(">\r\n                                    </a>\r\n                                </li" +
">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" tooltip=\"Robin\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4766), Tuple.Create("\"", 4820)
            
            #line 85 "..\..\Views\Product\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 4772), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ProductContent/img/user/09.jpg")
            
            #line default
            #line hidden
, 4772), false)
);

WriteLiteral(" alt=\"Follower\"");

WriteLiteral(" class=\"img-responsive img-circle thumb24\"");

WriteLiteral(@">
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
            <!-- END List group-->
            <div");

WriteLiteral(" class=\"panel panel-default hidden-xs hidden-sm\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"panel-title text-center\"");

WriteLiteral(">En Çok Takip Edilenler</div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(" ng-repeat=\"product in ctrl.topFollowedProducts\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"media-left media-middle\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5582), Tuple.Create("\"", 5638)
            
            #line 101 "..\..\Views\Product\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 5589), Tuple.Create<System.Object, System.Int32>(Url.Action("Detail","Product")
            
            #line default
            #line hidden
, 5589), false)
, Tuple.Create(Tuple.Create("", 5620), Tuple.Create("?id={{product.id}}", 5620), true)
);

WriteLiteral(">\r\n                                <img");

WriteLiteral(" ng-src=\"{{product.image_url}}\"");

WriteLiteral(" alt=\"{{product.name}}\"");

WriteLiteral(" class=\"media-object img-circle img-thumbnail thumb48\"");

WriteLiteral(">\r\n                            </a>\r\n                        </div>\r\n            " +
"            <div");

WriteLiteral(" class=\"media-body pt-sm\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"text-bold\"");

WriteLiteral(" title=\"{{product.name}}\"");

WriteLiteral(">\r\n                                {{(product.name.length >15 ? product.name.subs" +
"tring(0,15)+\'...\':product.name)  }}\r\n                                <div");

WriteLiteral(" class=\"text-sm text-muted\"");

WriteLiteral(">{{product.price}} TL</div>\r\n                            </div>\r\n                " +
"        </div>\r\n                    </div>\r\n                </div>\r\n            " +
"</div>\r\n\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"text-muted pull-right\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n                    </a>\r\n                    <h3");

WriteLiteral(" class=\"text-info\"");

WriteLiteral(">\r\n                        {{ctrl.product.name}}\r\n                        <span");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n                            <strong");

WriteLiteral(" style=\"color: black\"");

WriteLiteral(">Güncel Fiyat: <span");

WriteLiteral(" class=\"label label-success\"");

WriteLiteral(">{{ctrl.product.price +\' \'+ctrl.product.currency}}</span> </strong>\r\n            " +
"            </span>\r\n                    </h3>\r\n                    <div");

WriteLiteral(" class=\"text-center pv-xl\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" class=\"img-responsive\"");

WriteLiteral(" style=\"max-height: 600px; margin-left: auto; margin-right: auto\"");

WriteLiteral(" alt=\"...\"");

WriteLiteral(" ng-src=\"{{ctrl.product.image_url}}\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn\"");

WriteLiteral("> &nbsp; Takipçi <span");

WriteLiteral(" class=\"badge alert-info ng-binding pull-left\"");

WriteLiteral(">{{ctrl.product.follower_total}} </span></a>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" ng-click=\"ctrl.follow(product.url)\"");

WriteLiteral(" class=\"btn btn-success pull-right\"");

WriteLiteral(">Takip Et</a>\r\n                        </div>\r\n                    </div>\r\n      " +
"          </div>\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">\r\n                        <em");

WriteLiteral(" class=\"\"");

WriteLiteral("></em>\r\n                        <span");

WriteLiteral(" class=\"text-dark\"");

WriteLiteral("><b>{{ctrl.product.web_site_name}}</b></span>\r\n                    </p>\r\n\r\n      " +
"          </div>\r\n            </div>\r\n\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <h4>\r\n                        İlişkili Ürünler\r\n          " +
"          </h4>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-lg-4\"");

WriteLiteral(" ng-repeat=\"relationProduct in ctrl.relationProducts\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"panel widget\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"row row-table\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"col-xs-6 text-center\"");

WriteLiteral(">\r\n                                            <img");

WriteLiteral(" src=\"{{relationProduct.image_url}}\"");

WriteLiteral(" alt=\"Image\"");

WriteLiteral(" class=\"img-thumbnail img-circle img-responsive thumb96\"");

WriteLiteral(">\r\n                                        </div>\r\n                              " +
"          <div");

WriteLiteral(" class=\"col-xs-9\"");

WriteLiteral(">\r\n                                            <h5");

WriteLiteral(" class=\"mt0\"");

WriteLiteral(" title=\"{{relationProduct.name}}\"");

WriteLiteral(">{{relationProduct.name.length>25 ? relationProduct.name.substring(0,25)+\'...\' : " +
"relationProduct.name}}</h5>\r\n\r\n                                            <p");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">{{relationProduct.price}} TL</p>\r\n\r\n                                            " +
"<div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" ng-click=\"follow(relationProduct.url)\"");

WriteLiteral(" class=\"btn btn-success pull-right\"");

WriteLiteral(@">Takip Et</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 10003), Tuple.Create("\"", 10045)
, Tuple.Create(Tuple.Create("", 10009), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/productDetailService.js")
, 10009), false)
);

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
