#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Drop.Landing;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Product/Index.cshtml")]
    public partial class _Views_Product_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Product_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Product\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ProductLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(" ng-cloak");

WriteLiteral(" ng-controller=\"ProductSearchController as ctrl\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-lg-3 hidden-xs\"");

WriteLiteral(">\r\n            <!-- START List group-->\r\n            <ul");

WriteLiteral(" class=\"list-group\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row row-table pv-lg\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"m0 lead\"");

WriteLiteral(">1500</p>\r\n                            <p");

WriteLiteral(" class=\"m0\"");

WriteLiteral(">\r\n                                <small>ürün</small>\r\n                         " +
"   </p>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-6 text-center\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" data-sparkline=\"\"");

WriteLiteral(" data-bar-color=\"#23b7e5\"");

WriteLiteral(" data-height=\"60\"");

WriteLiteral(" data-bar-width=\"10\"");

WriteLiteral(" data-bar-spacing=\"6\"");

WriteLiteral(" data-chart-range-min=\"0\"");

WriteLiteral(" values=\"3,6,7,8,4,5\"");

WriteLiteral("></div>\r\n                        </div>\r\n                    </div>\r\n            " +
"    </li>\r\n                <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row row-table pv-lg\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"m0 lead\"");

WriteLiteral(">1.500 TL</p>\r\n                            <p");

WriteLiteral(" class=\"m0\"");

WriteLiteral(">\r\n                                <small>kazanç</small>\r\n                       " +
"     </p>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-6 text-center\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" data-sparkline=\"\"");

WriteLiteral(" data-type=\"line\"");

WriteLiteral(" data-height=\"60\"");

WriteLiteral(" data-width=\"80%\"");

WriteLiteral(" data-line-width=\"2\"");

WriteLiteral(" data-line-color=\"#7266ba\"");

WriteLiteral(" data-chart-range-min=\"0\"");

WriteLiteral(" data-spot-color=\"#888\"");

WriteLiteral(" data-min-spot-color=\"#7266ba\"");

WriteLiteral(" data-max-spot-color=\"#7266ba\"");

WriteLiteral("\r\n                                 data-fill-color=\"\"");

WriteLiteral(" data-highlight-line-color=\"#fff\"");

WriteLiteral(" data-spot-radius=\"3\"");

WriteLiteral(" values=\"7,3,4,7,5,9,4,4,7,5,9,6,4\"");

WriteLiteral(" data-resize=\"true\"");

WriteLiteral("></div>\r\n                        </div>\r\n                    </div>\r\n            " +
"    </li>\r\n                <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row row-table pv-lg\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"m0 lead\"");

WriteLiteral(">44</p>\r\n                            <p");

WriteLiteral(" class=\"m0\"");

WriteLiteral(">\r\n                                <small>yeni üye</small>\r\n                     " +
"       </p>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n                            <ul");

WriteLiteral(" class=\"list-inline text-center\"");

WriteLiteral(">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" tooltip=\"Katie\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2599), Tuple.Create("\"", 2653)
            
            #line 51 "..\..\Views\Product\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2605), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ProductContent/img/user/02.jpg")
            
            #line default
            #line hidden
, 2605), false)
);

WriteLiteral(" alt=\"Follower\"");

WriteLiteral(" class=\"img-responsive img-circle thumb24\"");

WriteLiteral(">\r\n                                    </a>\r\n                                </li" +
">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" tooltip=\"Cody\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2942), Tuple.Create("\"", 2996)
            
            #line 56 "..\..\Views\Product\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2948), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ProductContent/img/user/01.jpg")
            
            #line default
            #line hidden
, 2948), false)
);

WriteLiteral(" alt=\"Follower\"");

WriteLiteral(" class=\"img-responsive img-circle thumb24\"");

WriteLiteral(">\r\n                                    </a>\r\n                                </li" +
">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" tooltip=\"Tamara\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3287), Tuple.Create("\"", 3341)
            
            #line 61 "..\..\Views\Product\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3293), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ProductContent/img/user/03.jpg")
            
            #line default
            #line hidden
, 3293), false)
);

WriteLiteral(" alt=\"Follower\"");

WriteLiteral(" class=\"img-responsive img-circle thumb24\"");

WriteLiteral(">\r\n                                    </a>\r\n                                </li" +
">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" tooltip=\"Gene\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3630), Tuple.Create("\"", 3684)
            
            #line 66 "..\..\Views\Product\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3636), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ProductContent/img/user/04.jpg")
            
            #line default
            #line hidden
, 3636), false)
);

WriteLiteral(" alt=\"Follower\"");

WriteLiteral(" class=\"img-responsive img-circle thumb24\"");

WriteLiteral(">\r\n                                    </a>\r\n                                </li" +
">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" tooltip=\"Marsha\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3975), Tuple.Create("\"", 4029)
            
            #line 71 "..\..\Views\Product\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3981), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ProductContent/img/user/04.jpg")
            
            #line default
            #line hidden
, 3981), false)
);

WriteLiteral(" alt=\"Follower\"");

WriteLiteral(" class=\"img-responsive img-circle thumb24\"");

WriteLiteral(">\r\n                                    </a>\r\n                                </li" +
">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" tooltip=\"Robin\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4319), Tuple.Create("\"", 4373)
            
            #line 76 "..\..\Views\Product\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4325), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ProductContent/img/user/09.jpg")
            
            #line default
            #line hidden
, 4325), false)
);

WriteLiteral(" alt=\"Follower\"");

WriteLiteral(" class=\"img-responsive img-circle thumb24\"");

WriteLiteral(@">
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
            <!-- END List group-->
            ");

WriteLiteral("\r\n            ");

WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(" ng-init=\"ctrl.search()\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(" style=\"padding-bottom:10px\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Search for...\"");

WriteLiteral(" ng-keypress=\"ctrl.enterSearch($event)\"");

WriteLiteral(" ng-model=\"ctrl.keyword\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" ng-click=\"ctrl.refreshSearch()\"");

WriteLiteral(">Ara</button>\r\n                        </span>\r\n                    </div><!-- /i" +
"nput-group -->\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-6\"");

WriteLiteral(" ng-repeat=\"product in ctrl.searchProducts\"");

WriteLiteral(" ng-cloak");

WriteLiteral(" ng-show=\"ctrl.searchProducts.length>0\"");

WriteLiteral(">\r\n                    <!-- START widget-->\r\n                    <div");

WriteLiteral(" class=\"panel widget\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row row-table row-flush\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                                <picture");

WriteLiteral(" class=\"lateral-picture\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" ng-src=\"{{product.image_url}}\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                </picture>\r\n                            </div>" +
"\r\n                            <div");

WriteLiteral(" class=\"col-xs-12 align-middle p-lg\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(">Takip Et</a>\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6463), Tuple.Create("\"", 6519)
            
            #line 114 "..\..\Views\Product\Index.cshtml"
, Tuple.Create(Tuple.Create("", 6470), Tuple.Create<System.Object, System.Int32>(Url.Action("Detail","Product")
            
            #line default
            #line hidden
, 6470), false)
, Tuple.Create(Tuple.Create("", 6501), Tuple.Create("?id={{product.id}}", 6501), true)
);

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(">Detay</a>\r\n                                </div>\r\n                             " +
"   <p>\r\n                                    <span");

WriteLiteral(" class=\"text-lg\"");

WriteLiteral(">{{product.price}}</span>TL\r\n                                </p>\r\n              " +
"                  <p>\r\n                                    <strong");

WriteLiteral(" title=\"{{product.name}}\"");

WriteLiteral(">{{product.name.length>35 ? product.name.substring(0,35)+\'...\' : product.name}}</" +
"strong>\r\n                                </p>\r\n                                <" +
"span");

WriteLiteral(" class=\"pull-right btn btn-default\"");

WriteLiteral(">{{product.company}}</span>\r\n                            </div>\r\n                " +
"        </div>\r\n                    </div>\r\n                    <!-- END widget-" +
"->\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(" ng-show=\"ctrl.searchProducts.length == 0\"");

WriteLiteral(">\r\n                        Aradığınız kriterlerde ürün bulunamadı.\r\n             " +
"       </div>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-12 text-center\"");

WriteLiteral(">\r\n                    <pagination");

WriteLiteral(" ng-model=\"currentPage\"");

WriteLiteral("\r\n                                previous-text=\"<\"");

WriteLiteral("\r\n                                first-text=\"ilk\"");

WriteLiteral("\r\n                                last-text=\"son\"");

WriteLiteral("\r\n                                next-text=\">\"");

WriteLiteral("\r\n                                items-per-page=\"numPerPage\"");

WriteLiteral("\r\n                                total-items=\"totalCount\"");

WriteLiteral("\r\n                                max-size=\"maxSize\"");

WriteLiteral("\r\n                                ng-click=\"search()\"");

WriteLiteral("\r\n                                boundary-links=\"true\"");

WriteLiteral(">\r\n                    </pagination>\r\n                </div>\r\n            </div>\r" +
"\n            <!-- START bar chart-->\r\n            ");

WriteLiteral("\r\n            <!-- END bar chart-->\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"unwrap mv-lg\"");

WriteLiteral(">\r\n\r\n        <!-- START chart-->\r\n        ");

WriteLiteral("\r\n        <!-- END chart-->\r\n    </div>\r\n    <!-- START radial charts-->\r\n    ");

WriteLiteral("\r\n    <!-- END Multiple List group-->\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n   \r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 21909), Tuple.Create("\"", 21951)
, Tuple.Create(Tuple.Create("", 21915), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/productSearchService.js")
, 21915), false)
);

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
